version: '3.8'

services:
   php:
     build: .
     environment:
      - DISCODING_DB_HOST=db
      - DISCODING_DB_NAME=discoding
      - DISCODING_DB_USER=discoding
      - DISCODING_DB_PASSWORD=discoding
     volumes:
       - ./src:/var/www/html/
     ports:
       - 8080:80
   db:
     command: --default-authentication-plugin=mysql_native_password
     image: mysql:8.0
     volumes:
       - ./discoding.sql:/docker-entrypoint-initdb.d/1.sql
       - dbdata:/var/lib/mysql
     ports:
      - 3307:3306
     environment:
       MYSQL_ROOT_PASSWORD: discoding
       MYSQL_DATABASE: discoding
       MYSQL_USER: discoding
       MYSQL_PASSWORD: discoding
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - '9090:80'
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: discoding

volumes:
  dbdata: {}
